service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256
  environment: 
    BUCKET: serverlessawsbuckettest
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::*"

functions:
  getFiles: ${file(s3/functions.yml):getFiles}
  getData: ${file(s3/functions.yml):getData}
  postData: ${file(s3/functions.yml):postData}


# serverless config credentials -o --provider aws --key AKIAU2CUXYLYUBUKZEKU --secret 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
# serverless deploy -v
# serverless invoke -f hello -l
# serverless remove