service: nodeless

custom:
  ${file(config/custom.yml)}

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256
  environment:
    ${file(config/environment.yml)}
  iamRoleStatements:
    ${file(config/iamRoleStatements.yml)}
  vpc:
    ${file(config/vpc.yml)}

functions:
  # S3 functions
  s3GetFiles: ${file(s3/functions.yml):getFiles}
  s3GetData: ${file(s3/functions.yml):getData}
  s3PostData: ${file(s3/functions.yml):postData}

  # DynamoDB functions
  dynamoInsert: ${file(dynamo/functions.yml):insert}
  dynamoList: ${file(dynamo/functions.yml):list}
  dynamoGet: ${file(dynamo/functions.yml):get}
  dynamoUpdate: ${file(dynamo/functions.yml):update}
  dynamoDelete: ${file(dynamo/functions.yml):delete}

  # RDS
  rdsInsert: ${file(rds/functions.yml):insert}
  rdsList: ${file(rds/functions.yml):list}

resources:
  Resources:
    ${file(config/resources.yml)}

# serverless deploy -v
# serverless invoke -f hello -l
# serverless remove